version: '3.8'

services:
  dev-db:
    image: postgres:15
    container_name: rent_postgres
    restart: always
    ports:
      - '5436:5432'   # maps localhost:5436 -> container:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rentdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rent

volumes:
  pgdata:

networks:
  rent:
